swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
      # - application/json
      responses:
        "200":
          description: User profile retrieved successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get all transactions for the current month
      description: Retrieve a list of all transactions grouped by account for the current month.
      parameters:
        - in: query
          name: accountId
          type: string
          required: false
          description: Filter transactions by account ID
      produces:
        - application/json
      responses:
        "200":
          description: Transactions for the current month retrieved successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction"
          examples:
            application/json:
              - accountId: "string"
                transactionId: "string"
                date: "2024-08-29"
                description: "Shopping"
                amount: 100.50
                balance: 1000.75
                type: "expense"
                category: "Food"
                note: "Groceries"
              - accountId: "string"
                transactionId: "string"
                date: "2024-08-28"
                description: "Salary"
                amount: 200.00
                balance: 800.75
                type: "income"
                category: "Salary"
                note: "August salary"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Get transaction details
      description: Retrieve the details of a specific transaction by its ID
      parameters:
        - in: path
          name: transactionId
          type: string
          required: true
          description: The ID of the transaction to retrieve
      produces:
        - application/json
      responses:
        "200":
          description: Transaction details retrieved successfully
          schema:
            $ref: "#/definitions/TransactionDetail"
        "400":
          description: Invalid Fields
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error

    patch:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      summary: Update transaction details
      description: Update the details of a specific transaction (category, note)
      parameters:
        - in: path
          name: transactionId
          type: string
          required: true
          description: The ID of the transaction to update
        - in: body
          name: body
          description: Updated transaction details
          required: true
          schema:
            $ref: "#/definitions/TransactionUpdate"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successfully
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 0
              message:
                type: string
                example: "Transaction updated successfully"
              body:
                type: object
                properties:
                  accountId:
                    type: string
                  transactionId:
                    type: string
                  date:
                    type: string
                    format: date
                  description:
                    type: string
                  amount:
                    type: number
                    format: float
                  balance:
                    type: number
                    format: float
                  category:
                    type: string
                  note:
                    type: string
        "400":
          description: Invalid Fields
        "404":
          description: Transaction not found
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Transaction:
    type: object
    properties:
      accountId:
        type: string
      transactionId:
        type: string
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: number
        format: float
      balance:
        type: number
        format: float
      type:
        type: string
      category:
        type: string
      note:
        type: string
  TransactionDetail:
    type: object
    properties:
      accountId:
        type: string
      transactionId:
        type: string
      date:
        type: string
        format: date
      description:
        type: string
      amount:
        type: number
        format: float
      balance:
        type: number
        format: float
      type:
        type: string
      category:
        type: string
      note:
        type: string
  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
        description: Category of the transaction
      note:
        type: string
        description: Additional note about the transaction
